# Generated by Django 5.1 on 2024-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(help_text='enter your first name', max_length=30)),
                ('last_name', models.CharField(blank=True, help_text='enter your last name', max_length=30, null=True)),
                ('header', models.ImageField(blank=True, null=True, upload_to='users_header/')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users_avatar/')),
                ('username', models.CharField(help_text='enter your username', max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, help_text='enter your email address', max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='enter your phone number', max_length=11, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('account_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=8)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer not to say', 'Prefer not to say')], max_length=17)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
