# Generated by Django 5.1 on 2024-11-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_relation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 'relation'},
        ),
    ]
