# Generated by Django 5.1 on 2024-11-30 02:04

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_relation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=8, validators=[django.core.validators.RegexValidator(message='account type must be public or private only', regex='^(private|public)$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='enter your phone number', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='enter your username', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(message='Enter a valid username. contain only letters, numbers, and _', regex='^[\\w]+\\Z')]),
        ),
    ]
