# Generated by Django 5.1 on 2024-11-30 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_alter_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(max_length=300, upload_to='tweets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'mp4', 'webm', 'ogg'])]),
        ),
    ]
